networks:
  proxy_network:
    external: true

services:
  openhab:
    image: openhab/openhab:5.1.1 # Or your preferred version (4.1.0)
    container_name: openhab-${SITE_NAME}
    restart: always
    ports:
      - "${HTTP_PORT}:8080"
      - "${HTTPS_PORT}:8443"
    environment:
      USER_ID: "${USER_ID}"
      GROUP_ID: "${GROUP_ID}"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=${TIMEZONE}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DATA_PATH}/conf:/openhab/conf
      - ${DATA_PATH}/userdata:/openhab/userdata
      - ${DATA_PATH}/addons:/openhab/addons
    networks:
          - proxy_network